version: "3"

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      args:
        - APP=api-gateway
    restart: always
    ports:
      - 3000:3000

  user:
    container_name: user
    build:
      context: .
      args:
        - APP=user
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - db-user
    networks:
      - user-service-network
        
  db-user:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: microservices-user
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - user-service-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db-user
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - user-service-network

volumes:
  pgdata:
  pgadmin_data:

networks:
  user-service-network:
    driver: bridge