export const DATABASE_CONNECTION = Symbol.for('DATABASE_CONNECTION');
export const PAYMENT_MODEL = Symbol.for('PAYMENT_MODEL');
export const PAYMENT_REPOSITORY = Symbol.for('PAYMENT_REPOSITORY');
export const PAYMENT_SERVICE_KAFKA = Symbol.for('PAYMENT_SERVICE_KAFKA');
