export const ITEM_SEQUELIZE = Symbol.for('ITEM_SEQUELIZE');
export const ITEM_MODEL = Symbol.for('ITEM_MODEL');
export const ITEM_REPOSITORY = Symbol.for('ITEM_REPOSITORY');
export const ELASTIC_SERVICE_RABBITMQ = Symbol.for('ELASTIC_SERVICE_RABBITMQ');
export const ITEM_SERVICE_PAYMENT_RABBITMQ = Symbol.for(
  'ITEM_SERVICE_PAYMENT_RABBITMQ'
);
export const ITEM_SERVICE_ORDER_RABBITMQ = Symbol.for(
  'ITEM_SERVICE_ORDER_RABBITMQ'
);
