// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v5.28.3
// source: libs/shared/src/proto/item.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "item";

export interface DecreaseQuantityRequest {
  itemId: number;
  quantity: number;
}

export interface DecreaseQuantityResponse {
  success: boolean;
}

export const ITEM_PACKAGE_NAME = "item";

export interface ItemServiceClient {
  decreaseQuantity(request: DecreaseQuantityRequest): Observable<DecreaseQuantityResponse>;
}

export interface ItemServiceController {
  decreaseQuantity(
    request: DecreaseQuantityRequest,
  ): Promise<DecreaseQuantityResponse> | Observable<DecreaseQuantityResponse> | DecreaseQuantityResponse;
}

export function ItemServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["decreaseQuantity"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ItemService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ItemService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ITEM_SERVICE_NAME = "ItemService";
