// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.3.0
//   protoc               v5.28.3
// source: user.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Empty } from "./google/protobuf/empty";

export const protobufPackage = "user";

export enum GENDER {
  MALE = 0,
  FEMALE = 1,
  OTHER = 2,
  UNRECOGNIZED = -1,
}

export enum PROVIDER {
  GOOGLE = 0,
  GITHUB = 1,
  LOCAL = 2,
  UNRECOGNIZED = -1,
}

export enum ROLE {
  USER = 0,
  ADMIN = 1,
  UNRECOGNIZED = -1,
}

export interface User {
  id: string;
  email: string;
  password: string;
  fullName: string;
  gender: GENDER;
  provider: PROVIDER;
  avatar: string;
  role: ROLE[];
}

export interface CreateUserRequest {
  id: string;
  email: string;
  password: string;
  fullName: string;
  gender: GENDER;
  provider: PROVIDER;
  avatar: string;
  role: ROLE[];
}

export interface CreateUserResponse {
  status: boolean;
}

export interface UpdateUserRequest {
  id: string;
  email: string;
  password: string;
  fullName: string;
  gender: GENDER;
  provider: PROVIDER;
  avatar: string;
  role: ROLE[];
}

export interface UpdateUserResponse {
  status: boolean;
}

export interface DeleteUserRequest {
  id: string;
}

export interface DeleteUserResponse {
  status: boolean;
}

export interface GetUserByIdRequest {
  id: string;
}

export interface GetUserByIdResponse {
  user: User | undefined;
}

export interface GetUserByCredentialsRequest {
  email: string;
  password: string;
}

export interface GetUserByCredentialsResponse {
  user: User | undefined;
}

export interface GetAllUsersResponse {
  users: User[];
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  updateUser(request: UpdateUserRequest): Observable<UpdateUserResponse>;

  createUser(request: CreateUserRequest): Observable<CreateUserResponse>;

  deleteUser(request: DeleteUserRequest): Observable<DeleteUserResponse>;

  getUserById(request: GetUserByIdRequest): Observable<GetUserByIdResponse>;

  getUserByCredentials(request: GetUserByCredentialsRequest): Observable<GetUserByCredentialsResponse>;

  getAllUsers(request: Empty): Observable<GetAllUsersResponse>;
}

export interface UserServiceController {
  updateUser(
    request: UpdateUserRequest,
  ): Promise<UpdateUserResponse> | Observable<UpdateUserResponse> | UpdateUserResponse;

  createUser(
    request: CreateUserRequest,
  ): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  deleteUser(
    request: DeleteUserRequest,
  ): Promise<DeleteUserResponse> | Observable<DeleteUserResponse> | DeleteUserResponse;

  getUserById(
    request: GetUserByIdRequest,
  ): Promise<GetUserByIdResponse> | Observable<GetUserByIdResponse> | GetUserByIdResponse;

  getUserByCredentials(
    request: GetUserByCredentialsRequest,
  ): Promise<GetUserByCredentialsResponse> | Observable<GetUserByCredentialsResponse> | GetUserByCredentialsResponse;

  getAllUsers(request: Empty): Promise<GetAllUsersResponse> | Observable<GetAllUsersResponse> | GetAllUsersResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "updateUser",
      "createUser",
      "deleteUser",
      "getUserById",
      "getUserByCredentials",
      "getAllUsers",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
